### ISSUE TITLE
Todo before release

### ISSUE THREAD

**Issue by drewc5131** [OpenToontownTools/TTOpenLevelEditor#1]
- [x] fix lex/parser

- [x] fix panda collision traverser
- [x] implement optional auto compile to pdna
- [ ] maybe add yott styles?
